name: Commit mantap

on:
  push:
    branches:
      - main  
  schedule:
  - cron: "0 7 * * *"
jobs:
  auto_commit:
    runs-on: ubuntu-latest
    steps:
      - name: Hijau
        run: |
          echo "just another test"
