name: forest

on:

  push:
    branches:
      - main
      
  schedule:
    - cron: "0 8-17 * * *" # See https://crontab.guru/#0_7,9,11_*_*_1,3

jobs:
  auto_commit:
    runs-on: ubuntu-latest
    steps:
      - name: DEBUG 
        run: echo "::debug::Ref = ${{github.ref}}"
      - uses: actions/checkout@v3      
        with:
         persist-credentials: false
         fetch-depth: 0

      - name: Modify last update
        run: |
          d=`date '+%Y-%m-%dT%H:%M:%SZ'`
          echo $d > LAST_UPDATED
          
      - name: Commit changes
        run: |
          git config --local user.email "danangfirmino26@gmail.com"
          git config --local user.name "danangfir"
          git add -A
          
          arr[0]="chore(bot): 😂 "
          arr[1]="chore(bot): 😱 "
          arr[2]="chore(bot): 👿 "
          arr[3]="chore(bot): 💩 "
          arr[4]="chore(bot): 🙏 "
          arr[5]="chore(bot): 🙈 "
          arr[6]="chore(bot): 🐐 "
          arr[7]="chore(bot): 🤖 "
          arr[8]="chore(bot): 🟩 "
          arr[9]="chore(bot): 👻 "
          
          rand=$[$RANDOM % ${#arr[@]}]
          
          git commit -m "${arr[$rand]}"
          
      - name: GitHub Push
        uses: ad-m/github-push-action@v0.8.0
        with:
          directory: "."
          github_token: ${{ secrets.GITHUB_TOKEN }}
